version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8888"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "data_bace"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: